### ISSUE TITLE
[BUG] Taxonomy labels custom routing, interferes with 'Edit labels' route

### ISSUE THREAD

**Issue by sbonardt** [bolt/labels#44]
Hi,

don't know where to put this, but I figured I start out at the labels extension. I have a tags taxonomy type named: 'labels'

I want to view this in the frontend under the route: /locaties/{taxonomytype}/{slug}

Therefor I have a routing:

```
labels:
  path:  /locaties/{taxonomytype}/{slug}
  defaults:  { _controller: 'Bolt\Controllers\Frontend::taxonomy' }
  requirements:
    taxonomytype: 'labels'
```

This all works like a charm, however. I now can not access the eedit labels page for the labels extension: /bolt/extend/labels

the page loads with the following error:
```
NotFoundHttpException in RouterListener.php line 176:
No route found for "GET /bolt/extend/labels" 
```

Removing the addition in routing.yml solves it. But I want that routing! Where's the bug?

Using Bolt 3.2.9 and Labels 3.0.7
